services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inspa-app
    ports:
      - "8080:80"          # Apache exposed on http://localhost:8080
      - "5173:5173"        # Vite dev server for HMR
    volumes:
      - .:/var/www/html    # Mount source code into container
      - /var/www/html/vendor 
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: inspa-app_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inspa-app
      MYSQL_USER: aliona      
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
